server:
  address: 172.31.7.28
#  address: 192.168.1.15
  port: 8080
spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mariadb://localhost:3306/crudBoard
    username: river
    password: qkfka12
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#        use_sql_comments: true


logging.level:
  org.hibernate.SQL: debug

#  org.hibernate.type: trace