server:
  address: 172.31.13.30
#  address: localhost
  port: 8080
spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mariadb://localhost:3306/crudBoard
    username: river
    password: qkfka12
    driver-class-name: org.mariadb.jdbc.Driver
#    hikari:
#      driver-class-name: org.mariadb.jdbc.Driver
#      jdbc-url: jdbc:mariadb://3.35.140.92:3306/crudBoard
#      username: river
#      password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#        use_sql_comments: true


logging.level:
  org.hibernate.SQL: debug

#  org.hibernate.type: trace